name: Run Tests

on:
  push:
    branches:
      - main # main 브랜치에 push 시 이벤트 트리거
  pull_request:
    branches:
      - main # main 브랜치에 PR 생성 시 이벤트 트리거

jobs:
  test:
    runs-on: ubuntu-latest # GitHub Actions가 실행될 OS 설정

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # 코드 체크아웃

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Node.js 버전 설정

      - name: Install dependencies
        run: npm install # 의존성 설치

      - name: Run tests with coverage
        run: npm test -- --coverage # jest 실행 시 커버리지 리포트 생성 (--coverage 옵션 사용)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3 # Codecov 액션을 사용하여 커버리지 리포트 업로드
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Codecov 토큰 사용 (GitHub Secrets에 설정 필요)
          files: ./coverage/coverage-final.json # 업로드할 커버리지 리포트 파일 설정
          flags: unittests # 특정 플래그 설정 (선택 사항)
          name: code-coverage-report # 업로드된 리포트에 대한 이름 지정 (선택 사항)
